[2022-05-24 21:13:43,757] {processor.py:153} INFO - Started process (PID=36) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:13:43,777] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:13:43,778] {logging_mixin.py:115} INFO - [2022-05-24 21:13:43,778] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:13:46,497] {logging_mixin.py:115} INFO - [2022-05-24 21:13:46,483] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:13:46,504] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:13:46,587] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 2.835 seconds
[2022-05-24 21:14:16,999] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:17,001] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:14:17,006] {logging_mixin.py:115} INFO - [2022-05-24 21:14:17,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:17,614] {logging_mixin.py:115} INFO - [2022-05-24 21:14:17,607] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:14:17,616] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:17,643] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.650 seconds
[2022-05-24 21:14:47,904] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:47,906] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:14:47,908] {logging_mixin.py:115} INFO - [2022-05-24 21:14:47,908] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:49,099] {logging_mixin.py:115} INFO - [2022-05-24 21:14:49,088] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:14:49,106] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:14:49,193] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 1.300 seconds
[2022-05-24 21:15:19,534] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:19,540] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:15:19,542] {logging_mixin.py:115} INFO - [2022-05-24 21:15:19,541] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:19,986] {logging_mixin.py:115} INFO - [2022-05-24 21:15:19,978] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:15:19,988] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:20,022] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.495 seconds
[2022-05-24 21:15:50,525] {processor.py:153} INFO - Started process (PID=302) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:50,528] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:15:50,531] {logging_mixin.py:115} INFO - [2022-05-24 21:15:50,531] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:51,293] {logging_mixin.py:115} INFO - [2022-05-24 21:15:51,280] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:15:51,296] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:15:51,334] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.818 seconds
[2022-05-24 21:16:19,956] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:19,959] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:16:19,960] {logging_mixin.py:115} INFO - [2022-05-24 21:16:19,960] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:20,440] {logging_mixin.py:115} INFO - [2022-05-24 21:16:20,433] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 5, in <module>
    from dotenv import dotenv_values
ModuleNotFoundError: No module named 'dotenv'
[2022-05-24 21:16:20,442] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:20,459] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.512 seconds
[2022-05-24 21:16:43,380] {processor.py:153} INFO - Started process (PID=422) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:43,382] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:16:43,386] {logging_mixin.py:115} INFO - [2022-05-24 21:16:43,384] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:43,992] {logging_mixin.py:115} INFO - [2022-05-24 21:16:43,980] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 6, in <module>
    from mysql.connector import connect, Error
ModuleNotFoundError: No module named 'mysql'
[2022-05-24 21:16:43,995] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:16:44,032] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.659 seconds
[2022-05-24 21:17:14,903] {processor.py:153} INFO - Started process (PID=489) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:14,906] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:17:14,908] {logging_mixin.py:115} INFO - [2022-05-24 21:17:14,908] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:15,331] {logging_mixin.py:115} INFO - [2022-05-24 21:17:15,327] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 6, in <module>
    from mysql.connector import connect, Error
ModuleNotFoundError: No module named 'mysql'
[2022-05-24 21:17:15,332] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:15,349] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.455 seconds
[2022-05-24 21:17:15,935] {processor.py:153} INFO - Started process (PID=491) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:15,936] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:17:15,937] {logging_mixin.py:115} INFO - [2022-05-24 21:17:15,937] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:16,183] {logging_mixin.py:115} INFO - [2022-05-24 21:17:16,181] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:17:16,185] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:16,198] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.265 seconds
[2022-05-24 21:17:46,502] {processor.py:153} INFO - Started process (PID=558) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:46,506] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:17:46,508] {logging_mixin.py:115} INFO - [2022-05-24 21:17:46,508] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:46,909] {logging_mixin.py:115} INFO - [2022-05-24 21:17:46,903] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/etl_functions.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_functions.py", line 7, in <module>
    from flatten_json import flatten
ModuleNotFoundError: No module named 'flatten_json'
[2022-05-24 21:17:46,912] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:17:46,928] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.436 seconds
[2022-05-24 21:18:19,983] {processor.py:153} INFO - Started process (PID=626) to work on /opt/airflow/dags/etl_functions.py
[2022-05-24 21:18:19,985] {processor.py:641} INFO - Processing file /opt/airflow/dags/etl_functions.py for tasks to queue
[2022-05-24 21:18:19,987] {logging_mixin.py:115} INFO - [2022-05-24 21:18:19,986] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:18:19,992] {logging_mixin.py:115} INFO - [2022-05-24 21:18:19,992] {dagbag.py:300} INFO - File /opt/airflow/dags/etl_functions.py assumed to contain no DAGs. Skipping.
[2022-05-24 21:18:19,994] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_functions.py
[2022-05-24 21:18:20,020] {processor.py:161} INFO - Processing /opt/airflow/dags/etl_functions.py took 0.043 seconds
